// <auto-generated />
using System;
using GameHubAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameHubAPI.Migrations
{
    [DbContext(typeof(GameHubAPIDbContext))]
    [Migration("20231008213325_CriacaoInicial2")]
    partial class CriacaoInicial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("GameHubAPI.Models.AmizadeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("usuario1id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("usuario2id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuario1id");

                    b.HasIndex("usuario2id");

                    b.ToTable("Amizade");
                });

            modelBuilder.Entity("GameHubAPI.Models.BibliotecaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Biblioteca");
                });

            modelBuilder.Entity("GameHubAPI.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("GameHubAPI.Models.CompraJogo", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JogoId", "CompraId");

                    b.HasIndex("CompraId");

                    b.ToTable("CompraJogo");
                });

            modelBuilder.Entity("GameHubAPI.Models.CompraModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("GameHubAPI.Models.ConquistaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Conquista");
                });

            modelBuilder.Entity("GameHubAPI.Models.DesenvolvedoraModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Desenvolvedoras");
                });

            modelBuilder.Entity("GameHubAPI.Models.GameplayConquistaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("conquistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("gameplayid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("conquistaId");

                    b.HasIndex("gameplayid");

                    b.ToTable("GameplayConquista");
                });

            modelBuilder.Entity("GameHubAPI.Models.GameplayModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("jogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("jogoId");

                    b.HasIndex("usuarioid");

                    b.ToTable("Gameplay");
                });

            modelBuilder.Entity("GameHubAPI.Models.ImagemJogoModel", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("jogoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("jogoId");

                    b.ToTable("ImagemJogo");
                });

            modelBuilder.Entity("GameHubAPI.Models.JogoCategoria", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JogoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("JogosCategorias");
                });

            modelBuilder.Entity("GameHubAPI.Models.JogoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DesenvolvedoraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DesenvolvedoraId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("GameHubAPI.Models.NoticiaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Noticia");
                });

            modelBuilder.Entity("GameHubAPI.Models.ProgressoConquistaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("conquistaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("progresso")
                        .HasColumnType("REAL");

                    b.Property<int?>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("conquistaId");

                    b.HasIndex("usuarioid");

                    b.ToTable("ProgressoConquista");
                });

            modelBuilder.Entity("GameHubAPI.Models.PromocaoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoriaId");

                    b.ToTable("Promocao");
                });

            modelBuilder.Entity("GameHubAPI.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("dataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<bool>("usuarioAtivado")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("GameHubAPI.Models.AmizadeModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.UsuarioModel", "usuario1")
                        .WithMany()
                        .HasForeignKey("usuario1id");

                    b.HasOne("GameHubAPI.Models.UsuarioModel", "usuario2")
                        .WithMany()
                        .HasForeignKey("usuario2id");

                    b.Navigation("usuario1");

                    b.Navigation("usuario2");
                });

            modelBuilder.Entity("GameHubAPI.Models.BibliotecaModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.UsuarioModel", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("GameHubAPI.Models.CompraJogo", b =>
                {
                    b.HasOne("GameHubAPI.Models.CompraModel", "Compra")
                        .WithMany("CompraJogos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameHubAPI.Models.JogoModel", "Jogo")
                        .WithMany("CompraJogos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("GameHubAPI.Models.CompraModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameHubAPI.Models.GameplayConquistaModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.ConquistaModel", "conquista")
                        .WithMany()
                        .HasForeignKey("conquistaId");

                    b.HasOne("GameHubAPI.Models.GameplayModel", "gameplay")
                        .WithMany()
                        .HasForeignKey("gameplayid");

                    b.Navigation("conquista");

                    b.Navigation("gameplay");
                });

            modelBuilder.Entity("GameHubAPI.Models.GameplayModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.JogoModel", "jogo")
                        .WithMany()
                        .HasForeignKey("jogoId");

                    b.HasOne("GameHubAPI.Models.UsuarioModel", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");

                    b.Navigation("jogo");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("GameHubAPI.Models.ImagemJogoModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.JogoModel", "jogo")
                        .WithMany()
                        .HasForeignKey("jogoId");

                    b.Navigation("jogo");
                });

            modelBuilder.Entity("GameHubAPI.Models.JogoCategoria", b =>
                {
                    b.HasOne("GameHubAPI.Models.CategoriaModel", "Categoria")
                        .WithMany("JogosCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameHubAPI.Models.JogoModel", "Jogo")
                        .WithMany("JogosCategorias")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("GameHubAPI.Models.JogoModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.DesenvolvedoraModel", "Desenvolvedora")
                        .WithMany("Jogos")
                        .HasForeignKey("DesenvolvedoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desenvolvedora");
                });

            modelBuilder.Entity("GameHubAPI.Models.NoticiaModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("GameHubAPI.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameHubAPI.Models.ProgressoConquistaModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.ConquistaModel", "conquista")
                        .WithMany()
                        .HasForeignKey("conquistaId");

                    b.HasOne("GameHubAPI.Models.UsuarioModel", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");

                    b.Navigation("conquista");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("GameHubAPI.Models.PromocaoModel", b =>
                {
                    b.HasOne("GameHubAPI.Models.CategoriaModel", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("GameHubAPI.Models.CategoriaModel", b =>
                {
                    b.Navigation("JogosCategorias");
                });

            modelBuilder.Entity("GameHubAPI.Models.CompraModel", b =>
                {
                    b.Navigation("CompraJogos");
                });

            modelBuilder.Entity("GameHubAPI.Models.DesenvolvedoraModel", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("GameHubAPI.Models.JogoModel", b =>
                {
                    b.Navigation("CompraJogos");

                    b.Navigation("JogosCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
